language: python
python:
  - "3.6"
env:
  -DJANGO=2.2.2 DB=sqlite
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test